//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomoLine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        public ProductEntity()
        {
            this.tags = new HashSet<TagEntity>();
            this.transactions = new HashSet<TransactionEntity>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<double> min_order { get; set; }
        public string description { get; set; }
        public System.DateTime created_time { get; set; }
        public Nullable<double> price { get; set; }
        public int status { get; set; }
        public string photo_path { get; set; }
    
        public virtual CategoryEntity category { get; set; }
        public virtual UserEntity user { get; set; }
        public virtual ICollection<TagEntity> tags { get; set; }
        public virtual ICollection<TransactionEntity> transactions { get; set; }
    }
}
