//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomoLine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingEntity
    {
        public int trans_id { get; set; }
        public double rating { get; set; }
        public System.DateTime created_time { get; set; }
    
        public virtual TransactionEntity transaction { get; set; }
    }
}
