//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomoLine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEntity
    {
        public int id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
        public string status { get; set; }
        public Nullable<double> quantity { get; set; }
    
        public virtual ProductEntity product { get; set; }
        public virtual RatingEntity rating { get; set; }
        public virtual ReviewEntity review { get; set; }
        public virtual UserEntity user { get; set; }
    }
}
